### ISSUE TITLE
Voir la possibilité d'afficher uniquement les titres des sections

### ISSUE THREAD

**Issue by clementpr** [clementpr/moodle_course_modulenavigation#4]
Quel impact / faisabilité si ajout d'une option : 
"voir uniquement le titre des sections"

avec pour conséquence un block qui ressemblerait à cela :  https://moodle.org/plugins/block_course_contents

**Comment by nikpap** [comment]
Si j'ai bien compris, on voudrait l'afficher comme ça par défaut : 

![new course module navigation](https://cloud.githubusercontent.com/assets/2742143/20482225/cde8e512-afeb-11e6-93d3-8124a09baaee.JPG)

au lieu de ça : 

![old course module navigation](https://cloud.githubusercontent.com/assets/2742143/20482232/d66a7e12-afeb-11e6-87ee-e1bf65e57d27.JPG)

Sans possibilité de déplier le contenu. En cliquant sur le titre (eg sur présentation) on va se diriger vers la page "présentation.
